// <auto-generated />
using System;
using DataBaseSetup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBaseSetup.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201120164622_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataBaseSetup.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Pixels")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique();

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("DataBaseSetup.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecognitionId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DataBaseSetup.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("DataBaseSetup.Blob", b =>
                {
                    b.HasOne("DataBaseSetup.Photo", "Photo")
                        .WithOne("Pixels")
                        .HasForeignKey("DataBaseSetup.Blob", "PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DataBaseSetup.Photo", b =>
                {
                    b.HasOne("DataBaseSetup.Recognition", "Recognition")
                        .WithMany("Photos")
                        .HasForeignKey("RecognitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recognition");
                });

            modelBuilder.Entity("DataBaseSetup.Photo", b =>
                {
                    b.Navigation("Pixels");
                });

            modelBuilder.Entity("DataBaseSetup.Recognition", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
