// <auto-generated />
using System;
using DataBaseSetup;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataBaseSetup.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20201117164625_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataBaseSetup.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Pixels")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("DataBaseSetup.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PixelsId")
                        .HasColumnType("int");

                    b.Property<int?>("RecognitionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PixelsId");

                    b.HasIndex("RecognitionId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DataBaseSetup.Recognition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recognitions");
                });

            modelBuilder.Entity("DataBaseSetup.Photo", b =>
                {
                    b.HasOne("DataBaseSetup.Blob", "Pixels")
                        .WithMany()
                        .HasForeignKey("PixelsId");

                    b.HasOne("DataBaseSetup.Recognition", null)
                        .WithMany("Photo")
                        .HasForeignKey("RecognitionId");

                    b.Navigation("Pixels");
                });

            modelBuilder.Entity("DataBaseSetup.Recognition", b =>
                {
                    b.Navigation("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
